### ISSUE TITLE
Wrong date in history

### ISSUE THREAD

**Issue by ironjan** [brodeurlv/fastnfitness#170] opened 2020-08-13 22:21 UTC
**Describe your issue**
Hello, 

the current local date and time is 2020-08-14 00:08 . When entering an exercise, it is added for 2020-08-*13* 00:08.

Thank you. 
Your name

**To Reproduce**
1. Go to a 'Program' and start it around midnight.
2. Finish some exercises
3. Finish the program
4. Go to history

**Expected behavior**
Date and time of the exercise in history should be the same as the actual entering time.

**App Version:**
 - Version 0.19.3

**Additional context**
I'm not completely sure about the midnight part. Could also be a coincidence. 

This may be related to #168

**Comment by brodeurlv** [comment] 2020-08-15 07:56
Hi @ironjan,
it doesn't seems to be related to #168. #168 was only impacting the failed exercises. 
Date management in really a pain! 😱
Do you have the same behavior on all the exercises around this time? Or just some type? Or just the failed? 
Thanks.

**Comment by ironjan** [comment] 2020-08-27 09:40
Hi @brodeurlv , 

short update. I debugged this issue a little bit and found a very likely cause.

Better Reproduction:
1. Setup an emulator
2. Set the device time manually to something like 0:02
3. Set the device locale to be something non-GMT, e.g. Germany with GMT+2 at the moment
3. Start fastnfitness in debug
5. Split `DAORecord.java` line 192 as shown below [0]
4. Go to "free workout"
5. Enter a workout.

You should now see something like this:
![Bildschirmfoto zu 2020-08-27 11-11-16](https://user-images.githubusercontent.com/1698836/91421393-2db6af00-e856-11ea-9daf-30522317d196.png)

I was unable to reproduce the issue with unit tests/android connected tests. 

I strongly suspect that the problem is caused in the `DateConverter.dateToDBDateStr` and `DBDateStrToDate` methods. The former method can change the day: if the timezone is GMT+something, the `format` call substracts `something` hours which can result in a date change. The `format` call only converts the date and drops the time. When converting back via `DBDateStrToDate`, only the date is in DB. 

Unfortunately I wasn't able to find a fix ;)

[0] 
```
String value1 = DateConverter.dateToDBDateStr(pDate);
value.put(DAORecord.DATE, value1); // set breakpoint here
```

**Comment by brodeurlv** [comment] 2020-08-27 21:01
Hi, thank you for the reproduction steps. That will definitively help.
I'll have a look at it. Tell me if you find some fix on your side. Thanks.

Le jeu. 27 août 2020 à 11:40, Jan Lippert <notifications@github.com> a
écrit :

**Comment by ChrisJAllan** [comment] 2020-08-31 00:32
I have a fix for this over in my `time-fix` branch. I'll do some more testing with it before opening a pull request. Unfortunately, the old data cannot be easily fixed, at least not without some sort of one-time migration operation.

**Comment by brodeurlv** [comment] 2020-08-31 08:28
Hi @ChrisJAllan, at first sight, this looks great! Thank you for the work here. Let me know when you are ready to send the pull request!

**Closed** 2020-09-08 13:19 UTC
Labels: bug
