### ISSUE TITLE
Feature Request: Group Workout by Session

### ISSUE THREAD

**Issue by BeatLink** [brodeurlv/fastnfitness#103] opened 2019-12-27 00:38 UTC
It would be nice to be able to group workouts by dates or even a session for same day workouts. It would make it easier to see which set of exercises was done in a particular session

**Comment by brodeurlv** [comment] 2020-01-14 22:06
Hi @BeatLink, I don't understand your request. Can you provide more details or a user story ?
The records are already grouped by date.

**Comment by BeatLink** [comment] 2020-01-16 17:15
Ahh okay, I see what you mean. I guess what i was looking for was a similar way that open training handled the workouts. Basically you could group exercises into a specific workout session and then run the workout session. It would then go through each of the exercises of that session. Perhaps you could try out the app to see what i mean? Its opentraining on f-droid

**Comment by brodeurlv** [comment] 2020-01-21 22:28
Ok thanks for clarifying. So this is a duplicate of #82.
I'll track everything in #82 thread so.
Thanks

**Closed by brodeurlv** 2020-01-21 22:28 UTC
Labels: duplicate
